networks:
  bridge-network:
    driver: bridge

services:
  python:
    build:
      dockerfile: Dockerfile
    deploy:
      replicas: 4
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 8000
    networks:
      - bridge-network
    depends_on:
      postgres:
        condition: service_healthy
    command: ./run

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "tracker"
      POSTGRES_USER: "voldemar"
      POSTGRES_PASSWORD: "voldemar"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - bridge-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - python
      - postgres
    ports:
      - 4000:4000
    networks:
      - bridge-network
